debug: false
commands:
  echo:
    shortDescription: Echos input back to you.
    fullDescription: Takes in a string and sends it back to you.
    aliases:
      - cat
    permission: configcommands.echo
    then:
      string:
        type: String
        argumentInfo:
          subtype: greedy
        executes:
          - do <sender>.sendMessage(<string>)